hw1 commit
BlackenedJustice/testRepo pull request #39
Opened 2019-07-11 15:34 UTC by ntcrckr

completed hw1

2019-07-11 19:40 UTC, BlackenedJustice requested changes

2019-07-11 19:40 UTC, BlackenedJustice commented on Tasks/Pozdnyakov/PyTasks/HW1/1.py
> +  return y
Off-by-one

2019-07-11 19:40 UTC, BlackenedJustice commented on Tasks/Pozdnyakov/PyTasks/HW1/14.py
> +print((n//10)%10)
Неверно, это не число десятков:)

2019-07-11 19:40 UTC, BlackenedJustice commented on Tasks/Pozdnyakov/PyTasks/HW1/16.py
> +print()
Не работает.

2019-07-11 19:40 UTC, BlackenedJustice commented on Tasks/Pozdnyakov/PyTasks/HW1/4.py
> +print("Hello, ",pwd.getpwuid(os.getuid())[0],"!",sep='')
Неверно. Есть задача 4 и 4.1 там разные условия, а у тебя микс получился. Я понимаю что херня, но все равно другие переделывать, так что и эту переделай)

2019-07-11 19:40 UTC, BlackenedJustice commented on Tasks/Pozdnyakov/PyTasks/HW1/5.py
> +print(2*l+2*b*N+2*a*N+a)
Неверная формула (напутал с индексами)

2019-07-11 19:40 UTC, BlackenedJustice commented on Tasks/Pozdnyakov/PyTasks/HW1/6.py
> +print(sgn(x))
В математике sgn не так работает :)

2019-07-11 21:12 UTC, ntcrckr commented on Tasks/Pozdnyakov/PyTasks/HW1/14.py
> +print((n//10)%10)
вообще-то это оно и есть, не понимаю, о чем ты

2019-07-11 21:14 UTC, ntcrckr commented on Tasks/Pozdnyakov/PyTasks/HW1/16.py
> +print()
у меня все в порядке, мб ты тест неверный вбивал (A>B)

2019-07-13 14:54 UTC, BlackenedJustice approved these changes
Молодец!

2019-07-13 14:54 UTC, merged