PyTasks
BlackenedJustice/testRepo pull request #43
Opened 2019-07-12 22:09 UTC by CatherineFish

2019-07-13 15:20 UTC, BlackenedJustice requested changes

2019-07-13 15:20 UTC, BlackenedJustice commented on Tasks/Chekhonina/PyTasks/1.py
> +print(fib_2)
А функция где?)

2019-07-13 15:20 UTC, BlackenedJustice commented on Tasks/Chekhonina/PyTasks/13.py
> +s_2 = int(input())
А если 100 чисел будет?)

2019-07-13 15:20 UTC, BlackenedJustice commented on Tasks/Chekhonina/PyTasks/5.py
> +N = int(input())
А если 100 чисел будет?)

2019-07-13 15:20 UTC, BlackenedJustice commented on Tasks/Chekhonina/PyTasks/7.py
> +y2 = int(input())
А если 100 чисел будет?)

2019-07-13 15:20 UTC, BlackenedJustice commented on Tasks/Chekhonina/PyTasks/9.py
> +y_2 = int(input())
А если 100 чисел будет?)

2019-07-13 20:46 UTC, CatherineFish commented on Tasks/Chekhonina/PyTasks/1.py
> +print(fib_2)
Исправила!

2019-07-13 20:48 UTC, CatherineFish commented on Tasks/Chekhonina/PyTasks/13.py
> +s_2 = int(input())
Ты имеешь  в виду , что это неэкономный способ обработки входных данных?

2019-07-13 22:34 UTC, CatherineFish commented on Tasks/Chekhonina/PyTasks/13.py
> +s_2 = int(input())
Исправила!

2019-07-13 22:35 UTC, CatherineFish commented on Tasks/Chekhonina/PyTasks/5.py
> +N = int(input())
Исправила!

2019-07-13 22:37 UTC, CatherineFish commented on Tasks/Chekhonina/PyTasks/7.py
> +y2 = int(input())
Исправила!

2019-07-13 22:39 UTC, CatherineFish commented on Tasks/Chekhonina/PyTasks/9.py
> +y_2 = int(input())
Исправила!

2019-07-15 07:30 UTC, BlackenedJustice approved these changes

2019-07-15 07:30 UTC, merged